
>>># Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=sns.load_dataset("tips")

In [3]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# Regression

 the variables x and y can be used for regression analysis. x is considered the independent variable(s) and y is the dependent variable.
 
The goal of the regression analysis is to model the relationship between x and y in order to make predictions about the tip amount based on the total bill amount and size of the party. 

In [4]:
x=df[["total_bill","size"]]
y=df["tip"]

1.from sklearn.model_selection import train_test_split: This line imports the train_test_split function from the model_selection module of the scikit-learn library. The train_test_split function is used to split a dataset into training and testing sets.

2.X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state=1): This line splits the x and y data frames into four separate variables:

- X_train and y_train are the training datasets, which will be used to fit the regression model.
- X_test and y_test are the testing datasets, which will be used to evaluate the performance of the fitted model.
3.The test_size parameter specifies the proportion of the data that should be reserved for testing. In this case, test_size=0.4 means that 40% of the data will be used for testing and 60% will be used for training.

4.The random_state parameter is used to specify the random seed for the random number generator. This allows for reproducibility of the results, as the same random number generator will always generate the same split of data into training and testing sets. In this case, the random_state is set to 1.





In [5]:
from sklearn.model_selection import train_test_split                       
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state=1) # constant


1.from sklearn.linear_model import LinearRegression: This line imports the LinearRegression class from the linear_model module of the scikit-learn library. The LinearRegression class is used to perform linear regression analysis.

2.regression = LinearRegression(): This line creates an instance of the LinearRegression class and assigns it to the variable regression.

3.regression.fit(X_train, y_train): This line fits the linear regression model to the training data. The fit method takes as input the training data X_train and y_train, and adjusts the model parameters so as to minimize the residual sum of squares between the observed y_train values and the values predicted by the model for X_train. The resulting model can be used to make predictions on new data.

In [6]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()

regression.fit(X_train, y_train)

LinearRegression()

regression.score(x, y) calculates the R-squared value for the linear regression model regression applied to the full dataset x and y. The result will be a single number between 0 and 1, indicating the goodness of fit of the model to the data.

In [7]:
regression.score(x, y) # pridict accuracy

0.4584218310603574

regression.intercept_ returns the intercept of the linear regression model.

In a simple linear regression model with one independent variable, the equation of the regression line is given by:

y = b0 + b1 * x

where y is the dependent variable, x is the independent variable, b0 is the intercept, and b1 is the slope. The intercept is the value of y when x is equal to zero.

In multiple linear regression, the equation of the regression line is given by:

y = b0 + b1 * x1 + b2 * x2 + ... + bn * xn

where x1, x2, ..., xn are the independent variables, and b0, b1, b2, ..., bn are the coefficients. The intercept is the value of y when all the independent variables are equal to zero.

In this case, regression.intercept_ returns the intercept (b0) of the linear regression model regression.

In [8]:
regression.intercept_   # b0  # constant

0.6237635459366584

In [9]:
regression.coef_   # x1 ,x2

array([0.1111987, 0.0636649])

In [62]:
regression.predict([[12,3]])   # total.size

C:\Users\91852\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.14914265])

# Classification

In [63]:
df['day']

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ... 
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [64]:
df['size']

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [11]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
female=1,male=0   smoker no=1,smoker yes=0  ,day(sun) =1,thur=1,fri=1,sat=1,

In [65]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [12]:
df = pd.get_dummies(df,drop_first=True)      #   mon thue  wed thur fri sat sun

In [13]:
df

total_bill   tip  size  sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  \
0         16.99  1.01     2           1          1        0        0        1   
1         10.34  1.66     3           0          1        0        0        1   
2         21.01  3.50     3           0          1        0        0        1   
3         23.68  3.31     2           0          1        0        0        1   
4         24.59  3.61     4           1          1        0        0        1   
..          ...   ...   ...         ...        ...      ...      ...      ...   
239       29.03  5.92     3           0          1        0        1        0   
240       27.18  2.00     2           1          0        0        1        0   
241       22.67  2.00     2           0          0        0        1        0   
242       17.82  1.75     2           0          1        0        1        0   
243       18.78  3.00     2           1          1        0        0        0   

     time_Dinner  
0              1  
1              1  
2              1  
3              1  
4              1  
..           ...  
239            1  
240            1  
241            1  
242            1  
243            1  

[244 rows x 9 columns]

In [14]:
x = df.drop('sex_Female',axis=1)   # to effect the original dataset
y = df['sex_Female']      

In [15]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state=1)


# 1.SVM(Support Vector Machines)



from sklearn.svm import SVC: This line imports the SVC (Support Vector Classification) class from the svm module of the scikit-learn library. The SVC class is used to perform SVM classification.

model = SVC(): This line creates an instance of the SVC class and assigns it to the variable model.

model.fit(X_train, y_train): This line fits the SVM classifier to the training data. The fit method takes as input the training data X_train and y_train, and adjusts the model parameters so as to maximize the margin between the classes. The resulting model can be used to make predictions on new data.





In [16]:
from sklearn.svm import SVC

model = SVC()

model.fit(X_train,y_train)

SVC()

model.predict(X_test) is used to make predictions on the test data X_test using the SVM classifier model. The method returns an array of predictions, where each prediction corresponds to the class label for a given sample in X_test.

In [17]:
predictions = model.predict(X_test)

classification_report generates a summary of the classification performance, including precision, recall, f1-score, and support for each class. The precision is the ratio of true positive predictions to the sum of true positive and false positive predictions. The recall is the ratio of true positive predictions to the sum of true positive and false negative predictions. The f1-score is the harmonic mean of precision and recall. The support is the number of samples of each class in the test data.

confusion_matrix generates a confusion matrix, which is a table that summarizes the performance of a binary classifier. Each row of the matrix represents the actual class, while each column represents the predicted class. The elements of the matrix represent the number of samples that were correctly or incorrectly classified.

In [18]:
from sklearn.metrics import classification_report,confusion_matrix

The confusion matrix you've posted shows that the SVM classifier has made 63 true positive predictions and 35 false negative predictions. However, it seems like the classifier has not made any false positive or true negative predictions, which is indicated by the zeros in the second row of the matrix.

The true positive rate (recall) is 63/(63 + 35) = 0.64, which means that the classifier correctly identified 64% of the positive samples in the test data. The precision is not defined in this case, since there were no false positive predictions.

In [19]:
y_test

67     1
243    1
206    0
122    0
89     0
      ..
17     0
5      0
182    0
200    0
48     0
Name: sex_Female, Length: 98, dtype: uint8

In [20]:
print(confusion_matrix(y_test,predictions))  # 63 correct

[[63  0]
 [35  0]]


In [21]:
63+0+0+35

98

In [22]:
63/98

0.6428571428571429

In [23]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.64      1.00      0.78        63
           1       0.00      0.00      0.00        35

    accuracy                           0.64        98
   macro avg       0.32      0.50      0.39        98
weighted avg       0.41      0.64      0.50        98



C:\Users\91852\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\91852\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\91852\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [24]:
from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(y_test, predictions))

Accuracy: 0.6428571428571429


# 2. KNN(K-Nearest Neighbors)
1.Load the data

2.Choose the number of "K" and a distance metric

3.For a new observation, calculate the distance to all training examples

4.Sort the distances in ascending order

5.Select the top "K" training examples

6.Assign the class label based on the majority vote of the "K" nearest neighbors


In [25]:
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.metrics import accuracy_score

# Load the tips dataset
df=sns.load_dataset("tips")
df


total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [26]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(X_train,y_train)

KNeighborsClassifier()

In [27]:
predictions = model.predict(X_test)

C:\Users\91852\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [28]:
from sklearn.metrics import classification_report,confusion_matrix

In [29]:
print(confusion_matrix(y_test,predictions))

[[46 17]
 [24 11]]


In [30]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.66      0.73      0.69        63
           1       0.39      0.31      0.35        35

    accuracy                           0.58        98
   macro avg       0.53      0.52      0.52        98
weighted avg       0.56      0.58      0.57        98



In [31]:
from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(y_test, predictions))

Accuracy: 0.5816326530612245


# 3. NB(Naive Bayes Classifier)

Naive Bayes is a fast and simple algorithm and it is particularly useful when dealing with large amounts of data. However, it makes the assumption that all features are independent of each other, which may not always be the case in real-world data. Despite this limitation, Naive Bayes has been found to perform well in many practical applications.

In [32]:

from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(X_train,y_train)

GaussianNB()

In [33]:
predictions = model.predict(X_test)

In [34]:
from sklearn.metrics import classification_report,confusion_matrix

In [35]:
y_test

67     1
243    1
206    0
122    0
89     0
      ..
17     0
5      0
182    0
200    0
48     0
Name: sex_Female, Length: 98, dtype: uint8

In [36]:
print(confusion_matrix(y_test,predictions))

[[46 17]
 [24 11]]


In [37]:
46+17+24+11

98

In [38]:
46+11

57

In [39]:
57/98

0.5816326530612245

In [40]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.66      0.73      0.69        63
           1       0.39      0.31      0.35        35

    accuracy                           0.58        98
   macro avg       0.53      0.52      0.52        98
weighted avg       0.56      0.58      0.57        98



In [41]:
from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(y_test, predictions))

Accuracy: 0.5816326530612245


# 4. DT(Decision Tree)

A decision tree is a tree-like model used for prediction and classification tasks in machine learning. It consists of internal nodes that represent features or attributes, branches that represent the possible values of these features, and leaves that represent the class labels. The goal of a decision tree is to split the data into homogeneous groups, such that the samples in each group are as similar as possible with respect to the target variable.

In [69]:
from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier()

model.fit(X_train,y_train)

DecisionTreeClassifier()

In [70]:
predictions = model.predict(X_test)

In [71]:
from sklearn.metrics import classification_report,confusion_matrix

In [72]:
y_test

67     1
243    1
206    0
122    0
89     0
      ..
17     0
5      0
182    0
200    0
48     0
Name: sex_Female, Length: 98, dtype: uint8

In [73]:
print(confusion_matrix(y_test,predictions))

[[39 24]
 [22 13]]


In [76]:
39+24+22+13

98

In [77]:
39+13

52

In [78]:
52/98

0.5306122448979592

In [79]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.64      0.62      0.63        63
           1       0.35      0.37      0.36        35

    accuracy                           0.53        98
   macro avg       0.50      0.50      0.50        98
weighted avg       0.54      0.53      0.53        98



In [80]:
from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(y_test, predictions))

Accuracy: 0.5306122448979592


# 5. RF(Random Forest)

Random Forest is an ensemble machine learning algorithm that builds multiple decision trees and combines their predictions to make a final prediction. It is a type of supervised learning algorithm that is used for both regression and classification problems.

In [52]:
from sklearn.ensemble import RandomForestClassifier  # best correct ,time consuming,accurate 

model=RandomForestClassifier()

model.fit(X_train,y_train)

RandomForestClassifier()

In [53]:
predictions = model.predict(X_test)

In [54]:
from sklearn.metrics import classification_report,confusion_matrix

In [55]:
y_test

67     1
243    1
206    0
122    0
89     0
      ..
17     0
5      0
182    0
200    0
48     0
Name: sex_Female, Length: 98, dtype: uint8

In [56]:
print(confusion_matrix(y_test,predictions))

[[38 25]
 [23 12]]


In [57]:
41+22+23+12

98

In [58]:
41+12

53

In [59]:
53/98

0.5408163265306123

In [60]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.62      0.60      0.61        63
           1       0.32      0.34      0.33        35

    accuracy                           0.51        98
   macro avg       0.47      0.47      0.47        98
weighted avg       0.52      0.51      0.51        98



In [61]:
from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(y_test, predictions))

Accuracy: 0.5102040816326531
